stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "togotrip-frontend"
  GCR_IMAGE_NAME: "southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1"

build:
  stage: build
  image: google/cloud-sdk:alpine
  script:
    - gcloud config set project inbound-rune-421414
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - gcloud auth configure-docker southamerica-east1-docker.pkg.dev
    - docker build -t $GCR_IMAGE_NAME .
    - docker push $GCR_IMAGE_NAME

# deploy:
#   stage: deploy
#   image: google/cloud-sdk:alpine
#   script:
#     - gcloud config set project inbound-rune-421414
#     - gcloud auth login
#     - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
#     - gcloud run deploy togotrip-frontend --image=$GCR_IMAGE_NAME --platform=managed --region=southamerica-east1 --allow-unauthenticated
