stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "togotrip-frontend"
  GCR_IMAGE_NAME: "southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend"

build:
  stage: build
  image: docker:latest
  services:
    - docker:latest
  script:
    - docker build -t togotrip-frontend .
    - docker tag togotrip-frontend southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend
    - echo '$GCP_SERVICE_ACCOUNT_KEY' | gcloud auth activate-service-account gitlab@inbound-rune-421414.iam.gserviceaccount.com --key-file=_json_key
    - docker push southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file <(echo $GCP_SERVICE_ACCOUNT_KEY)
    - gcloud config set project inbound-rate-421414
    - gcloud container clusters get-credentials $GCP_CLUSTER_NAME --zone $GCP_ZONE
    - kubectl set image deployment/your-deployment-name your-container-name=$GCR_IMAGE_NAME
