stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "togotrip-frontend"
  GCR_IMAGE_NAME: "gcr.io/inbound-rune-421414/togotrip-frontend"

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t togotrip-frontend .
    - docker tag togotrip-frontend $GCR_IMAGE_NAME
    - echo $GCP_SERVICE_ACCOUNT_KEY | docker login -u _json_key --password-stdin https://gcr.io
    - docker push $GCR_IMAGE_NAME

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file <(echo $GCP_SERVICE_ACCOUNT_KEY)
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $GCP_CLUSTER_NAME --zone $GCP_ZONE
    - kubectl set image deployment/your-deployment-name your-container-name=$GCR_IMAGE_NAME
