image: google/cloud-sdk:latest

stages:
  - build
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > service_account.json
  - apk add --update --no-cache curl python3 py3-crcmod bash libc6-compat
  - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
  - tar xzf google-cloud-sdk.tar.gz -C /root
  - /root/google-cloud-sdk/install.sh --usage-reporting=false --path-update=true --bash-completion=true --disable-installation-options
  - /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=service_account.json
  - /root/google-cloud-sdk/bin/gcloud config set project inbound-rune-421414
  - /root/google-cloud-sdk/bin/gcloud auth configure-docker southamerica-east1-docker.pkg.dev

variables:
  DOCKER_IMAGE_NAME: "togotrip-frontend"
  GCR_IMAGE_NAME: "southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1"

build:
  stage: build
  image: docker:latest
  services:
    - docker:latest
  script:
    # - gcloud config set project inbound-rune-421414
    # - echo "$GCP_SERVICE_ACCOUNT_KEY" > service_account.json
    # - gcloud auth activate-service-account --key-file service_account.json
    # - gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet
    - docker build -t southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1 .
    - docker push southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1


# build:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:latest
#   script:
#     - gcloud config set project inbound-rune-421414
#     - echo "$GCP_SERVICE_ACCOUNT_KEY" > service_account.json
#     - gcloud auth activate-service-account --key-file service_account.json
#     - gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet
#     - docker build -t southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1 .
#     - docker push southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:v1


# deploy:
#   stage: deploy
#   image: google/cloud-sdk:alpine
#   script:
#     - gcloud config set project inbound-rune-421414
#     - gcloud auth login
#     - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
#     - gcloud run deploy togotrip-frontend --image=$GCR_IMAGE_NAME --platform=managed --region=southamerica-east1 --allow-unauthenticated
