apiVersion: apps/v1
kind: Deployment
metadata:
  name: togotrip-frontend-workload
spec:
  replicas: 3  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: togotrip-frontend
  template:
    metadata:
      labels:
        app: togotrip-frontend
    spec:
      containers:
      - name: togotrip-frontend
        image: southamerica-east1-docker.pkg.dev/inbound-rune-421414/togotrip-frontend/togotrip-frontend:latest  # Imagem Docker para o seu container
        ports:
        - containerPort: 8080  #